name: Code Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

permissions: {}

jobs:
  code-analysis:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@1508160852fb97248640997f7cfb38da241df0ba # v2.9.1
        with:
          channel: 'stable'
      - name: Prepare dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Check Dart code formatting
        run: |
          dart format . -o none --set-exit-if-changed
      - name: Analyze Dart code
        run: |
          flutter analyze .
      - name: Generate dartdoc
        run: |
          dart pub global activate dartdoc
          dart pub global run dartdoc .
  test:
    needs: [code-analysis]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: ['']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@1508160852fb97248640997f7cfb38da241df0ba # v2.9.1
        with:
          channel: 'stable'
          flutter-version: ${{ matrix.flutter-version }}
      - name: Prepare dependencies
        run: |
          flutter --version
          flutter pub get
      - name: Test
        run: flutter test
